### PR TITLE
Improve install process

### PR DESCRIPTION
**Pull request by ericpoe**
This change pulls apart our existing installers and makes it so we can use various installers and updaters depending on what we're wanting to do with any changes.

This came about from me needing to rebuild my Symfony side or my JS side when I don't need to rebuild both sides.

This also makes the docker directory just be responsible for running certain scripts in docker. For example, our current way of installing an environment is `docker/app docker/install` and the `docker/install` script cannot be run on its own; in this new way, we would run `php_install.sh` as a standalone or dockerized as `docker/app ./bin/php_install.sh`.

### CODE REVIEW

**Comment by akoebbe** [comment]
I think putting these scripts in /bin would be a better location, so that we're not filling up root with our custom scripts. What do you think?

**Comment by akoebbe** [comment]
I wonder if we need to be explicit for windows dev environments with docker since the instructions require bash.

**Comment by ericpoe** [comment]
> I wonder if we need to be explicit for windows dev environments with docker since the instructions require bash.

I'm not sure how to go about doing that since I don't have a Windows machine to try this out on. Do you know of anyone who can try it out? We would need Windows batch files for the same scripts. I'll create a ticket for this.

**Comment by ericpoe** [comment]
> I think putting these scripts in /bin would be a better location, so that we're not filling up root with our custom scripts. What do you think?

I like it. Done!

**Pull request merged**
