### PR TITLE
74 Add help text property for attribute fields

### PR DESCRIPTION
**Pull request by uplyft**
This update should give you the ability to add custom help text (of max-length 255) to any Client or Partner Attribute. The uri to try that out is: /#/admin/attributes/client ...

Once you have added help text to any attributes, you should then see a little icon with a tooltip next to its corresponding label on the detail page found under Client Management or Partner Management. Those uris are: /#/clients + /#/partners

Of course we can display these hints however you wish. 2 screenshots are attached to see v1.

image

image

Let me know what you think!

### CODE REVIEW

**Comment by akoebbe** [comment]
@uplyft This is great! Is the 255 a limitation of the tooltip library or just the input field?

**Comment by uplyft** [comment]
> @uplyft This is great! Is the 255 a limitation of the tooltip library or just the input field?

@akoebbe I'm unaware of any limitation on the tooltip library. This is just how I set up the field. I can change that to longtext or anything else you prefer.

**Comment by akoebbe** [comment]
Sorry for the delay on this. If the annotation is `text` then let's change the UI field to a textarea.

**Comment by uplyft** [comment]
> @uplyft Sorry for the delay on this. If the annotation is `text` then let's change the UI field to a textarea.

@akoebbe No problem, this is now done.

**Pull request merged**
