### PR TITLE
Soft delete list option entities

### PR DESCRIPTION
**Pull request by ffeliks**
This PR is aimed to fix issue #84 

In the `ListOptionController@destroy` method I have replaced the `remove()` with `setDeletedAt()` since all `listOption` entities are soft deletable.

Also slightly altered the display logic for categories and products to not display any entries when the category is deleted

### CODE REVIEW

**Comment by akoebbe** [comment]
@ffeliks Thank you so much for this PR. I'm really sorry, but this fix ended up being stubmled upon in #141, because we didn't have the soft delete library configured correctly and I forgot to go back through to see if we needed to close related issues. Luckily this will still count for your Hacktoberfest even though it will be rejected.

I will go through the other issues and make sure we don't do this again. Again, I'm sorry this was already fixed and not updated.

FWIW, this is the library we are using to handle soft deletes: http://atlantic18.github.io/DoctrineExtensions/doc/softdeleteable.html

**Comment by ffeliks** [comment]
I believe this is still an issue. You will no longer get the SQL error however the entity will be deleted.

To reproduce simply start on a clean slate and running all the fixtures. Proceed to delete the product category and notice that the row from the database will be deleted. This will also create a problem when navigating to the products page.

Regarding the hacktoberfest I believe the PR has to be marked with a specific label in order for it to count.
> Your PR has not yet been accepted by a maintainer. A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it.

**Comment by akoebbe** [comment]
@ffeliks I think you're right there is still something up here. I'm looking in to it now.

Also. I added the label.

**Comment by akoebbe** [comment]
Ok. For me the row still exists but has a `deletedAt` date which the library does automatically and will get excluded from doctrine queries by the library.

image

After deleting the category though, going to the Product Management page will give a generic 500 error because it can't find the category for some of the products. Here's what I think we should do. Let's do a check when a category is deleted and see if there are products associated with it. If so, we should throw a `UserInterfaceException` (which is shown to the user in prod) that they can't delete a category that has been used and that they should deactivate it instead.

What would you think about that?

**Comment by ffeliks** [comment]
Yes sounds good! I'll be happy to solve this problem :)

**Pull request closed without merging**
